:eq=≡
:neq=≢
:and=∧
:or=∨
:implies=⇒
:follows=⇐
:not=¬
:def=≔
:lambda=ꟛ
:forall=∀
:exists=∃
:end=□
:arrow=→
:trans=↦
:in=∈
:nat=ℕ
:backtick=`
^0=⁰
^1=¹
^2=²
^3=³
^4=⁴
^5=⁵
^6=⁶
^7=⁷
^8=⁸
^9=⁹
_0=₀
_1=₁
_2=₂
_3=₃
_4=₄
_5=₅
_6=₆
_7=₇
_8=₈
_9=₉

# from agda-input.el
:all=∀
:ex=∃
:exn=∄
:emptyset=∅
:intersection=∩
:union=∪
:compl=∁
:supseteq=⊇
:subseteq=⊆
:supset=⊃
:subset=⊂
:member=∈
:nin=∉
:wedge=∧
:vee=∨
:nand=⊼
:norbar=⊽
:xor=⊻
:perp=⊥
:top=⊤
:turnstile=⊢
:turnstile_n=⊬
:semicolon=⨾
:cdot=⋅
:bullet=•
:bullet_w=◦
:star=⋆
:times=×
:slash_dot=⊘
:div_times=⊗
:plus_circle=⊕
:minus_circle=⊖
:divide_circle=⊘
:dot_circle=⊙
:ast_circle=⊛
:eq_circle=⊜
:dash_circle=⊝
:sqrt=√
:cbrt=∛
:inf=∞
:div=÷
:pm=±
:mp=∓
:partial=∂
:nabla=∇
:del=∇
:integral=∫
:integral2=∬
:integral3=∭
:integral4=∮
:integral5=∯
:integral6=∰
:pi=π
:PI=Π
:sigma=σ
:SIGMA=Σ
:phi=φ
:PHI=Φ
:psi=ψ
:PSI=Ψ
:alpha=α
:ALPHA=Α
:beta=β
:BETA=Β
:gamma=γ
:GAMMA=Γ
:delta=δ
:DELTA=Δ
:epsilon=ε
:EPSILON=Ε
:zeta=ζ
:ZETA=Ζ
:eta=η
:ETA=Η
:theta=θ
:THETA=Θ
:iota=ι
:IOTA=Ι
:kappa=κ
:KAPPA=Κ
:lambda=λ
:LAMBDA=Λ
:mu=μ
:MU=Μ
:nu=ν
:NU=Ν
:xi=ξ
:XI=Ξ
:omicron=ο
:OMICRON=Ο
:rho=ρ
:RHO=Ρ
:tau=τ
:TAU=Τ
:upsilon=υ
:UPSILON=Υ
:chi=χ
:CHI=Χ
:omega=ω
:OMEGA=Ω
:left_arrow=←
:left_arrow_double=⇐
:right_arrow=→
:right_arrow_double=⇒
:up_arrow=↑
:up_arrow_double=⇑
:down_arrow=↓
:down_arrow_double=⇓
:updown_arrow=↕
:updown_arrow_double=⇕
:left_right_arrow=↔
:left_right_arrow_double=⇔
:up_left_arrow=↖
:up_right_arrow=↗
:down_right_arrow=↘
:down_left_arrow=↙
:mapsto=↦
:not_right_arrow=↛
:not_left_arrow=↚
:approx=≈
:not_approx=≉
:similar=∼
:not_similar=≁
:equiv=≡
:not_equiv=≢
:less_eq=≤
:greater_eq=≥
:less=<
:greater=>
:not_less=≮
:not_greater=≯
:sqsubseteq=⊑
:sqsupseteq=⊒
:not_sqsubseteq=⋢
:not_sqsupseteq=⋣
:precedes=≺
:succeeds=≻
:precedes_eq=≼
:succeeds_eq=≽
:ll=≪
:gg=≫
:dagger=†
:ddagger=‡
:parallel=∥
:not_parallel=∦
:perpendicular=⊥
:divides=∣
:not_divides=∤
:angle=∠
:angle_r=⊾
:angle_c=⊿
:qed=∎
:dblvertbar=‖
:cross=✗
:checkmark=✓
:natural=♮
:flat=♭
:sharp=♯
:eighth_note=♪
:ell=ℓ
:wp=℘
:aleph=ℵ
:beth=ℶ
:gimel=ℷ
:daleth=ℸ
:open_paren=(
:close_paren=)
:open_bracket=[
:close_bracket=]
:open_brace={
:close_brace=}
:open_angle=⟨
:close_angle=⟩
:open_double_bracket=⟦
:close_double_bracket=⟧
:open_ceil=⌈
:close_ceil=⌉
:open_floor=⌊
:close_floor=⌋
:em_dash=—
:en_dash=–
:double_prime=″
:triple_prime=‴
:quad_prime=⁗
:rev_prime=‵
:rev_double_prime=‶
:rev_triple_prime=‷
